Feature/block non GitHub domain
shinenic/a-tree pull request #27
Opened 2021-09-09 03:10 UTC by KKzLEO

2021-09-09 11:31 UTC, shinenic requested changes
Maybe we choose `optional permission` for enterprise GitHub instead of matching all route.

2021-09-16 18:03 UTC, KKzLEO commented
> Maybe we choose `optional permission` for enterprise GitHub instead of matching all route.

Sure, now we're using chrome extension's context menu to control enabling/disabling a-tree in specific domain, but we still need to set `matches` to `all_urls`

2021-09-17 02:17 UTC, shinenic commented on src/background.js
> -const activeTabUrlMemo = {}
I think we still need this one.

2021-09-17 02:20 UTC, shinenic commented on src/background.js
> +chrome.runtime.onInstalled.addListener(() => {
Cool!!
btw, maybe we can add the contextMenu option only on `non-GitHub domain` pages?

2021-09-17 02:21 UTC, shinenic commented on public/manifest.json
> +  "permissions": ["webNavigation", "contextMenus"],
Nice work, don't forget to update `README.md`

2021-09-17 02:24 UTC, shinenic commented on src/background.js
> +chrome.runtime.onInstalled.addListener(() => {
not sure if it is possible (or necessary

2021-09-17 02:30 UTC, shinenic commented on src/background.js
> -const activeTabUrlMemo = {}
or the SPA will not work lol

2021-09-17 14:27 UTC, shinenic commented on src/index.js
> +    body {
`html` for Mac?

2021-09-17 16:32 UTC, merged